### ISSUE TITLE
Python issues (Pop 21.10)

### ISSUE THREAD

**Issue by spxak1** [x2es/bt-dualboot#3]
Hello, 

thanks for your hard work. This is the first attempt. Here's the output:

~~~
otheos@kepler:~$ sudo bt-dualboot --win /mnt -l
Traceback (most recent call last):
  File "/usr/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bt-dualboot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 342, in main
    app.run()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 252, in run
    self.list_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 173, in list_devices
    devices=sync_manager.devices_both_synced(),
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_sync_manager/bt_sync_manager.py", line 111, in devices_both_synced
    index = self._index_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_sync_manager/bt_sync_manager.py", line 61, in _index_devices
    linux_devices   = get_linux_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/devices.py", line 40, in get_devices
    return [bluetooth_device_factory(device_path) for device_path in get_devices_paths()]
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/devices.py", line 40, in <listcomp>
    return [bluetooth_device_factory(device_path) for device_path in get_devices_paths()]
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/bluetooth_device_factory.py", line 55, in bluetooth_device_factory
    info = extract_info(device_info_path)
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/bluetooth_device_factory.py", line 38, in extract_info
    "class":        config.get("General", "Class"),
  File "/usr/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'class' in section: 'General'
~~~

Thanks.

**Comment by x2es** [comment]
Thank you for the report!

I have published bugfix `v1.0.1`. Update pip package and try again.

```console
$ sudo pip install -U bt-dualboot
$ bt-dualboot --version
bt-dualboot 1.0.1
```

For some reason in your case some of `/var/lib/bluetooth/ADAPTER_MAC/DEVICE_MAC/info` config doesn't contain `[General]/Class=` option.

Is your devices is common Bluetooth device or LE (low energy)?

For testing I have two kinds of configs:
 * https://github.com/x2es/bt-dualboot/blob/master/tests/bt_linux/data_samples/bt_sample_01/A4:6B:6C:9D:E2:FB/A4:BF:C6:D0:E5:FF/info
 * https://github.com/x2es/bt-dualboot/blob/master/tests/bt_linux/data_samples/bt_sample_01/A4:6B:6C:9D:E2:FB/B6:C2:D3:E5:F2:0D/info

It would be helpful if you share with me configs from `/var/lib/bluetooth/.../info` which have notable difference from mine. Especially config which doesn't contain `Class=` attribute in `[General]` section. Private values may be removed, I'd like to see structure.

**Comment by spxak1** [comment]
Thanks for the update. I still get the same:

~~~
root@kepler:/home/otheos# sudo bt-dualboot --win /mnt -l
Traceback (most recent call last):
  File "/usr/local/bin/bt-dualboot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 342, in main
    app.run()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 252, in run
    self.list_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/cli/app.py", line 173, in list_devices
    devices=sync_manager.devices_both_synced(),
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_sync_manager/bt_sync_manager.py", line 111, in devices_both_synced
    index = self._index_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_sync_manager/bt_sync_manager.py", line 61, in _index_devices
    linux_devices   = get_linux_devices()
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/devices.py", line 40, in get_devices
    return [bluetooth_device_factory(device_path) for device_path in get_devices_paths()]
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/devices.py", line 40, in <listcomp>
    return [bluetooth_device_factory(device_path) for device_path in get_devices_paths()]
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/bluetooth_device_factory.py", line 55, in bluetooth_device_factory
    info = extract_info(device_info_path)
  File "/usr/local/lib/python3.9/dist-packages/bt_dualboot/bt_linux/bluetooth_device_factory.py", line 39, in extract_info
    "pairing_key":  config.get("LinkKey", "Key"),
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'LinkKey'
~~~

Here's my Logitech MX3 mouse:
~~~
root@kepler:/home/otheos# cat /usr/lib/bluetooth/
bluetoothd   mpris-proxy  obexd        
root@kepler:/home/otheos# cat /var/lib/bluetooth/
84:7B:57:91:BC:BF/ 88:D8:2E:E5:40:65/ 98:3B:8F:F3:1E:06/ 
84:7B:57:E7:B7:4B/ 8C:A9:82:FD:1E:F6/ C0:B6:F9:03:04:43/ 
root@kepler:/home/otheos# cat /var/lib/bluetooth/84\:7B\:57\:E7\:B7\:4B/
44:16:22:A4:FC:30/ cache/             DA:5B:4A:88:50:AD/ 
90:7F:61:0A:68:F9/ D7:43:6B:11:F7:82/ settings           
root@kepler:/home/otheos# cat /var/lib/bluetooth/84\:7B\:57\:E7\:B7\:4B/DA\:5B\:4A\:88\:50\:AD/info 
[General]
Name=MX Anywhere 3
Appearance=0x03c2
AddressType=static
SupportedTechnologies=LE;
Trusted=true
Blocked=false
WakeAllowed=true
Services=00001800-0000-1000-8000-00805f9b34fb;00001801-0000-1000-8000-00805f9b34fb;0000180a-0000-1000-8000-00805f9b34fb;0000180f-0000-1000-8000-00805f9b34fb;00001812-0000-1000-8000-00805f9b34fb;00010000-0000-1000-8000-011f2000046d;

[IdentityResolvingKey]
Key=7493D746CAD1FEEE7D9E1C26ADC7CB34

[SlaveLongTermKey]
Key=C55074C3D43FA22176FB46DAD187CBFE
Authenticated=2
EncSize=16
EDiv=0
Rand=0

[ConnectionParameters]
MinInterval=6
MaxInterval=9
Latency=44
Timeout=216

[DeviceID]
Source=2
Vendor=1133
Product=45093
Version=20
~~~

This is already converted using my manual method in my page.

I hope this helps. 

Thanks again for taking the time.

**Comment by Tactile-Taco** [comment]
I am having this same issue
